import os

BOT_API_KEY = "5143130886:AAH4cTPuqHO6jmFVA2LWsMDuTeoQrYN0iFw"
SPREADSHEET_ID = "1tHGntYp9MQB5wcrAZ7oBQ_knSRP6zifeuyrA1uzPZMo"

#BOT_API_KEY = os.getenv("BOT_API_KEY")
#SPREADSHEET_ID = os.getenv("SPREADSHEET_ID")

